version: '3.7'

networks:
  sbe-js-template:
    ipam:
      config:
      - subnet: 172.18.1.0/24

services:
  e2e:
    image: node:alpine
    container_name: e2e
    working_dir: /ws
    entrypoint: /bin/sh -c '(cd e2e && npm install; tail -f)'
    volumes:
    - .:/ws
    environment:
      TZ: BRT3BRST,M11.1.6/23:59:59,M2.3.6/23:59:59
    networks:
      sbe-js-template:
        ipv4_address: 172.18.1.2

  hub:
    container_name: hub
    image: selenium/hub:2.53.1-beryllium
    environment:
      TZ: BRT3BRST,M11.1.6/23:59:59,M2.3.6/23:59:59
    ports:
     - 4444:4444
    networks:
      sbe-js-template:
        ipv4_address: 172.18.1.3

  firefox:
    container_name: firefox
    image: selenium/node-firefox:2.53.1-beryllium
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      TZ: BRT3BRST,M11.1.6/23:59:59,M2.3.6/23:59:59
    ports:
    - 9000
    networks:
      sbe-js-template:
        ipv4_address: 172.18.1.4

  chrome:
    container_name: chrome
    image: selenium/node-chrome:2.53.1-beryllium
    ports:
    - 9000
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      TZ: BRT3BRST,M11.1.6/23:59:59,M2.3.6/23:59:59
    networks:
      sbe-js-template:
        ipv4_address: 172.18.1.5

